adds general functionality

diff --git a/bin/bonita_wm b/bin/bonita_wm
--- a/bin/bonita_wm
+++ b/bin/bonita_wm
@@ -19,11 +19,11 @@ set -e
 #===  BASIC CONFIGURATIONS CHECKS ==============================================
 
 if [ -z $BONITA_INSTALL_DIR ]; then
-  echo
-  echo "Can't work unless i know where bonita is installed"
-  echo "Please set BONITA_INSTALL_DIR to point to this directory."
-  echo
-  exit 1
+    echo
+    echo "Can't work unless i know where Bonita BPM is installed"
+    echo "Please set \$BONITA_INSTALL_DIR to point to this directory."
+    echo
+    exit 1
 fi
 
 
@@ -39,14 +39,14 @@ ROOT_DIR="$(dirname $(readlink ${BASH_SOURCE[*]}))/.."
 #  DESCRIPTION:  Represents the directory where bonita holds workspaces.
 #===============================================================================
 
-BONITA_WS_DIR="${BONITA_INSTALL_DIR/workspace}"
+BONITA_WS_DIR="${BONITA_INSTALL_DIR}/workspace"
 
 #===  VARIABLE =================================================================
 #         NAME:  WS_DIR
 #  DESCRIPTION:  Represents the directory where the script holds its workspaces.
 #===============================================================================
 
-WS_DIR="${ROOT_DIR}/workspaces"
+[ -z $WS_DIR ] && WS_DIR="${ROOT_DIR}/workspaces"
 
 #===  VARIABLE =================================================================
 #         NAME:  EXAMPLE
@@ -55,6 +55,10 @@ WS_DIR="${ROOT_DIR}/workspaces"
 
 EXAMPLE="${ROOT_DIR}/default.tar.gz"
 
+#===  VARIABLE =================================================================
+#         NAME:  SCPT_VERSION
+#  DESCRIPTION:  Represents the version of the script
+#===============================================================================
 
 SCPT_VERSION="0.1"
 
@@ -63,13 +67,17 @@ SCPT_VERSION="0.1"
 #  DESCRIPTION:  Display usage information.
 #===============================================================================
 
-function usage ()
+function usage()
 {
-  echo "Usage :  $0 [options] [--]
+    echo "Usage :  $0 [options] [--]
 
-  Options:
-  -h|help       Display this message
-  -v|version    Display script version"
+    Options:
+    -h|help           Display this message
+    -v|version        Display script version
+    -i|initialize     Enable workspace management
+    -l|list           List available workspaces
+    -n|new <name>     Create new workspace
+    -e|enable <name>  Enable given workspace"
 
 }
 
@@ -84,7 +92,7 @@ function usage ()
 
 function _script_is_not_handling_workspaces()
 {
-  [ ! -h $BONITA_WS_DIR/default ]
+    [ ! -h $BONITA_WS_DIR/default ]
 }
 
 #===  HELPER ===================================================================
@@ -92,10 +100,10 @@ function _script_is_not_handling_workspaces()
 #  DESCRIPTION:  checks if a given workspace has alreaddy been created
 #===============================================================================
 
-function _workspace_exists ()
+function _workspace_exists()
 {
-  local ws_name=$1;
-  [ -d "${WS_DIR}/$ws_name" ]
+    local ws_name=$1;
+    [ -d "${WS_DIR}/$ws_name" ]
 }
 
 #===  FUNCTION  ================================================================
@@ -103,17 +111,16 @@ function _workspace_exists ()
 #  DESCRIPTION:  create new bonita workspace
 #===============================================================================
 
-function new_workspace ()
+function new_workspace()
 {
-  local ws_name=$1
+    local ws_name=$1
 
-  [ -z $ws_name ] && echo "need a name for the new workspace" && exit 1
+    [ -z $ws_name ] && echo "Need a name for the new workspace." && exit 1
 
-  mkdir "${WS_DIR}/${ws_name}"
+    mkdir "${WS_DIR}/${ws_name}"
 
-  tar -xzf $EXAMPLE -C "${WS_DIR}/${ws_name}"
-
-}    # ----------  end of function usage  ----------
+    tar -xzf $EXAMPLE -C "${WS_DIR}/${ws_name}"
+}
 
 
 #===  FUNCTION  ================================================================
@@ -123,31 +130,36 @@ function new_workspace ()
 
 function enable_workspace()
 {
-  local ws_name=$1
+    local ws_name=$1
 
-  [ -z $ws_name ] && echo "need a workspace to enable" && exit 1
+    [ -z $ws_name ] && echo "Need a workspace to enable" && exit 1
 
-  if _script_is_not_handling_workspaces; then
-    echo 'Need to initialize script first' &&  exit 1;
-  fi
+    if _script_is_not_handling_workspaces; then
+        echo 'Need to initialize script first' &&  exit 1;
+    fi
 
-  if _workspace_exists $ws_name; then
-    rm "${BONITA_WS_DIR}/default" && \
-      ln -s "${WS_DIR}/${ws_name}" "${BONITA_WS_DIR}/default" && \
-      echo "${ws_name} successfully enabled"
-  else
-    echo "workspace not available." && exit 1
-  fi
+    if _workspace_exists $ws_name; then
+
+        # First, let's remove old symlink
+        rm "${BONITA_WS_DIR}/default"
+
+        # Now we can enable the requested workspace
+        ln -s "${WS_DIR}/${ws_name}" "${BONITA_WS_DIR}/default"
+
+        echo "${ws_name} successfully enabled"
+    else
+        echo "workspace not available." && exit 1
+    fi
 }
 
 #===  FUNCTION  ================================================================
 #         NAME:  list_workspaces
-#  DESCRIPTION:  list available workspaces
+#  DESCRIPTION:  Lists available workspaces.
 #===============================================================================
 
 function list_workspaces()
 {
-  ls $WS_DIR;
+    ls -1 $WS_DIR;
 }
 
 #===  FUNCTION  ================================================================
@@ -156,46 +168,54 @@ function list_workspaces()
 #                This means the script will start handling workspaces for bonita.
 #===============================================================================
 
-function initialize_workspace_management ()
+function initialize_workspace_management()
 {
-  if [ -d $BONITA_WS_DIR/default ]; then
+    if [ ! -h "${BONITA_WS_DIR}/default" ]; then
+        # This means default workspace is still in place so we should
+        # back it up and re-enable it.
 
-    # This means default workspace is still in place so we should back it up
-    # as default and enable it again.
+        echo "Backing up default workspace in case you had anything done ;)"
+        mv "${BONITA_WS_DIR}/default" "${WS_DIR}/default"
 
-    echo "Backing up default workspace in case you had anything done ;)"
-    mv "${BONITA_WS_DIR}/default" $WS_DIR
-
-    echo "Enabling default workspace"
-    enable_workspace 'default'
-  fi
+        echo "Enabling default workspace"
+        ln -s "${WS_DIR}/default" "${BONITA_WS_DIR}/default"
+    else
+        echo "Workspace management seems to be already initialized."
+    fi
 }
 
+#===  FUNCTION  ================================================================
+#         NAME:  print_version
+#  DESCRIPTION:  Prints script version
+#===============================================================================
 
+function print_version()
+{
+    echo "$0 -- Version $SCPT_VERSION"
+}
 
 #-----------------------------------------------------------------------
 #  Handle command line arguments
 #-----------------------------------------------------------------------
 
-while getopts ":hviln:" opt; do
-  case $opt in
+while getopts ":hviln:e:" opt; do
+    case $opt in
 
-    h|help   ) usage; exit 0 ;;
+        h|help      ) usage; exit 0 ;;
 
-    v|version) echo "$0 -- Version $SCPT_VERSION"; exit 0 ;;
+        v|version   ) print_version; exit 0 ;;
 
-    i|initialize) initialize_workspace_management ;;
+        i|initialize) initialize_workspace_management ;;
 
-    l|list   ) list_workspaces ;;
+        l|list      ) list_workspaces; exit 0 ;;
 
-    n|new    ) new_workspace $OPTARG ;;
+        n|new       ) new_workspace $OPTARG ;;
 
-    e|enable ) enable_workspace $OPTARG ;;
+        e|enable    ) enable_workspace $OPTARG ;;
 
-    * )  echo -e "\n  Option does not exist : $OPTARG\n" usage; exit 1; ;;
+        * )  echo -e "\n  Option does not exist : $OPTARG\n" usage; exit 1; ;;
 
-  esac
+    esac
 done
 
 shift $(($OPTIND-1))
-
